-- Phase 8 SOC 2 evidence exports.
-- Monthly packs are generated by protected ops cron routes and written with
-- the service role. No client-side RLS policy is defined for this table.

create table soc2_evidence_export (
  id uuid primary key default gen_random_uuid(),
  export_type text not null check (export_type in ('monthly_soc2')),
  period_start timestamptz not null,
  period_end timestamptz not null,
  generated_at timestamptz not null default now(),
  status text not null check (status in ('complete','needs_review')),
  evidence_pack jsonb not null,
  review_item_count int not null default 0 check (review_item_count >= 0),
  provider_quota_red_count int not null default 0 check (provider_quota_red_count >= 0),
  active_ops_admin_count int not null default 0 check (active_ops_admin_count >= 0),
  created_at timestamptz not null default now(),
  unique (export_type, period_start, period_end)
);

create index soc2_evidence_export_generated_idx
  on soc2_evidence_export(generated_at desc);

create index soc2_evidence_export_status_idx
  on soc2_evidence_export(status, generated_at desc);

alter table soc2_evidence_export enable row level security;

create function public.get_soc2_audit_event_counts(
  p_period_start timestamptz,
  p_period_end timestamptz
)
returns table(event_type text, event_count bigint)
language sql
security definer
set search_path = public
as $$
  select ae.event_type, count(*)::bigint as event_count
  from public.audit_event ae
  where ae.created_at >= p_period_start
    and ae.created_at < p_period_end
  group by ae.event_type
  order by ae.event_type;
$$;

revoke all on function public.get_soc2_audit_event_counts(
  timestamptz,
  timestamptz
) from public;

grant execute on function public.get_soc2_audit_event_counts(
  timestamptz,
  timestamptz
) to service_role;

create table ops_admin_access_review (
  id uuid primary key default gen_random_uuid(),
  period_start timestamptz not null,
  period_end timestamptz not null,
  generated_at timestamptz not null,
  status text not null default 'pending' check (status in ('pending','approved','changes_required')),
  active_admins jsonb not null,
  active_admin_count int not null default 0 check (active_admin_count >= 0),
  owner_count int not null default 0 check (owner_count >= 0),
  admin_count int not null default 0 check (admin_count >= 0),
  evidence_export_id uuid references soc2_evidence_export(id),
  reviewed_by uuid references user_profile(id),
  reviewed_at timestamptz,
  review_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (period_start, period_end)
);

create index ops_admin_access_review_period_idx
  on ops_admin_access_review(period_start desc, period_end desc);

create index ops_admin_access_review_status_idx
  on ops_admin_access_review(status, generated_at desc);

alter table ops_admin_access_review enable row level security;

create trigger ops_admin_access_review_set_updated_at
  before update on ops_admin_access_review
  for each row execute function set_updated_at();

create function public.open_ops_admin_access_review(
  p_period_start timestamptz,
  p_period_end timestamptz,
  p_generated_at timestamptz,
  p_active_admins jsonb,
  p_active_admin_count int,
  p_owner_count int,
  p_admin_count int,
  p_evidence_export_id uuid,
  p_trigger text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_review_id uuid;
begin
  insert into public.ops_admin_access_review (
    period_start,
    period_end,
    generated_at,
    status,
    active_admins,
    active_admin_count,
    owner_count,
    admin_count,
    evidence_export_id
  )
  values (
    p_period_start,
    p_period_end,
    p_generated_at,
    'pending',
    p_active_admins,
    p_active_admin_count,
    p_owner_count,
    p_admin_count,
    p_evidence_export_id
  )
  on conflict (period_start, period_end) do update set
    generated_at = case when ops_admin_access_review.status = 'pending'
      then excluded.generated_at else ops_admin_access_review.generated_at end,
    status = ops_admin_access_review.status,
    active_admins = case when ops_admin_access_review.status = 'pending'
      then excluded.active_admins else ops_admin_access_review.active_admins end,
    active_admin_count = case when ops_admin_access_review.status = 'pending'
      then excluded.active_admin_count else ops_admin_access_review.active_admin_count end,
    owner_count = case when ops_admin_access_review.status = 'pending'
      then excluded.owner_count else ops_admin_access_review.owner_count end,
    admin_count = case when ops_admin_access_review.status = 'pending'
      then excluded.admin_count else ops_admin_access_review.admin_count end,
    evidence_export_id = case when ops_admin_access_review.status = 'pending'
      then excluded.evidence_export_id else ops_admin_access_review.evidence_export_id end,
    reviewed_by = ops_admin_access_review.reviewed_by,
    reviewed_at = ops_admin_access_review.reviewed_at,
    review_note = ops_admin_access_review.review_note
  returning id into v_review_id;

  insert into public.audit_event (
    actor_user_id,
    event_type,
    target_type,
    target_id,
    metadata
  )
  values (
    null,
    'ops_admin.access_review_opened',
    'ops_admin_access_review',
    v_review_id,
    jsonb_build_object(
      'trigger', p_trigger,
      'period_start', p_period_start,
      'period_end', p_period_end,
      'evidence_export_id', p_evidence_export_id,
      'active_admin_count', p_active_admin_count,
      'owner_count', p_owner_count,
      'admin_count', p_admin_count
    )
  );

  return v_review_id;
end;
$$;

revoke all on function public.open_ops_admin_access_review(
  timestamptz,
  timestamptz,
  timestamptz,
  jsonb,
  int,
  int,
  int,
  uuid,
  text
) from public;

create function public.create_soc2_evidence_export(
  p_period_start timestamptz,
  p_period_end timestamptz,
  p_generated_at timestamptz,
  p_status text,
  p_evidence_pack jsonb,
  p_review_item_count int,
  p_provider_quota_red_count int,
  p_active_admins jsonb,
  p_active_admin_count int,
  p_owner_count int,
  p_admin_count int,
  p_trigger text
)
returns table(export_id uuid, access_review_id uuid)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_export_id uuid;
  v_access_review_id uuid;
  v_review_completed boolean := false;
begin
  select status <> 'pending'
    into v_review_completed
  from public.ops_admin_access_review
  where period_start = p_period_start
    and period_end = p_period_end
  for update;

  v_review_completed := coalesce(v_review_completed, false);

  insert into public.soc2_evidence_export (
    export_type,
    period_start,
    period_end,
    generated_at,
    status,
    evidence_pack,
    review_item_count,
    provider_quota_red_count,
    active_ops_admin_count
  )
  values (
    'monthly_soc2',
    p_period_start,
    p_period_end,
    p_generated_at,
    p_status,
    p_evidence_pack,
    p_review_item_count,
    p_provider_quota_red_count,
    p_active_admin_count
  )
  on conflict (export_type, period_start, period_end) do update set
    generated_at = case when v_review_completed
      then soc2_evidence_export.generated_at else excluded.generated_at end,
    status = case when v_review_completed
      then soc2_evidence_export.status else excluded.status end,
    evidence_pack = case when v_review_completed
      then soc2_evidence_export.evidence_pack else excluded.evidence_pack end,
    review_item_count = case when v_review_completed
      then soc2_evidence_export.review_item_count else excluded.review_item_count end,
    provider_quota_red_count = case when v_review_completed
      then soc2_evidence_export.provider_quota_red_count else excluded.provider_quota_red_count end,
    active_ops_admin_count = case when v_review_completed
      then soc2_evidence_export.active_ops_admin_count else excluded.active_ops_admin_count end
  returning id into v_export_id;

  select public.open_ops_admin_access_review(
    p_period_start,
    p_period_end,
    p_generated_at,
    p_active_admins,
    p_active_admin_count,
    p_owner_count,
    p_admin_count,
    v_export_id,
    p_trigger
  )
  into v_access_review_id;

  insert into public.audit_event (
    actor_user_id,
    event_type,
    target_type,
    target_id,
    metadata
  )
  values (
    null,
    'soc2.evidence_export_generated',
    'soc2_evidence_export',
    v_export_id,
    jsonb_build_object(
      'trigger', p_trigger,
      'period_start', p_period_start,
      'period_end', p_period_end,
      'status', p_status,
      'access_review_id', v_access_review_id,
      'evidence_preserved', v_review_completed,
      'review_item_count', p_review_item_count,
      'provider_quota_red_count', p_provider_quota_red_count,
      'active_ops_admin_count', p_active_admin_count
    )
  );

  export_id := v_export_id;
  access_review_id := v_access_review_id;
  return next;
end;
$$;

revoke all on function public.create_soc2_evidence_export(
  timestamptz,
  timestamptz,
  timestamptz,
  text,
  jsonb,
  int,
  int,
  jsonb,
  int,
  int,
  int,
  text
) from public;

grant execute on function public.create_soc2_evidence_export(
  timestamptz,
  timestamptz,
  timestamptz,
  text,
  jsonb,
  int,
  int,
  jsonb,
  int,
  int,
  int,
  text
) to service_role;

create function public.attest_ops_admin_access_review(
  p_review_id uuid,
  p_reviewer_user_id uuid,
  p_status text,
  p_review_note text,
  p_request_id text,
  p_trace_id text,
  p_actor_ip inet default null,
  p_actor_user_agent text default null
)
returns table(review_id uuid, status text, reviewed_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_status not in ('approved', 'changes_required') then
    raise exception 'invalid_access_review_status' using errcode = '22023';
  end if;

  if not exists (
    select 1
    from public.ops_admin oa
    where oa.user_id = p_reviewer_user_id
      and oa.revoked_at is null
      and oa.role in ('owner', 'admin')
  ) then
    raise exception 'ops_admin_access_required' using errcode = '42501';
  end if;

  update public.ops_admin_access_review ar
  set
    status = p_status,
    reviewed_by = p_reviewer_user_id,
    reviewed_at = now(),
    review_note = nullif(p_review_note, '')
  where ar.id = p_review_id
  returning ar.id, ar.status, ar.reviewed_at
  into review_id, status, reviewed_at;

  if review_id is null then
    raise exception 'access_review_not_found' using errcode = 'P0002';
  end if;

  insert into public.audit_event (
    actor_user_id,
    actor_ip,
    actor_user_agent,
    event_type,
    target_type,
    target_id,
    metadata
  )
  values (
    p_reviewer_user_id,
    p_actor_ip,
    p_actor_user_agent,
    'ops_admin.access_review_attested',
    'ops_admin_access_review',
    review_id,
    jsonb_build_object(
      'status', status,
      'request_id', p_request_id,
      'trace_id', p_trace_id
    )
  );

  return next;
end;
$$;

revoke all on function public.attest_ops_admin_access_review(
  uuid,
  uuid,
  text,
  text,
  text,
  text,
  inet,
  text
) from public;

grant execute on function public.attest_ops_admin_access_review(
  uuid,
  uuid,
  text,
  text,
  text,
  text,
  inet,
  text
) to service_role;
